### ISSUE TITLE
[1.21.1] mushroom chopping still trying to access forge tags

### ISSUE THREAD

**Issue by Lucky-56** [hammertater/treechop#324]
**Minecraft version:** 1.21.1
**NeoForge version:** 21.1.162
**Mod version:** 0.19.3

`#forge` should be `#c`

```toml

[compatibility.trees.hugeMushrooms]
	logs = ["#forge:mushroom_stems"]
	leaves = ["#forge:mushroom_caps"]

```
